### ISSUE TITLE
How to update the config of an existing Scrubbable()?

### ISSUE THREAD

**Issue by MrBiscuit** [mhmd-22/scrubbable#1]
Hi, how to update an existing Scrubbable dynamically? without adding new listeners to the same input element? for example, width = 28 by default, but I want the width to be "full" when the "alt(⌥)" modifier key is pressed; step = 1 by default, but step = 8 when the  "shift⇧" modifier key is pressed

Or is there a way to simply reset or delete an existing Scrubbable so I can replace it with a new one with different config?

**Comment by qurafi** [comment]
Thank you for opening an issue. Glad someone uses my code :D

You can change any value by using the object returned by `Scrubbable` function. Here's an example
```javascript
// use the returned object to change any value
const input_scrub = Scrubbable(input);


function onKey(e) {
    const isKeyDown = e.type == "keydown";

    input_scrub.width = e.altKey && isKeyDown ? input.offsetWidth : 8;

    input_scrub.step = e.shiftKey && isKeyDown ? 8 : 1;
}

window.addEventListener("keydown", onKey);
window.addEventListener("keyup", onKey);
```
If you want to delete an existing Scrubbable you could use `.destroy` method

There's no currently way to add custom logic before scrubbing(e.g. enable scrubbing only on shiftKey) but we may add that as `onBeforeScrub` hook function in the feature! **Feel free to open PR to implement this**

**Comment by MrBiscuit** [comment]
Wow! Thank you sooo much for the detailed reply good sir, Scrubbable library has been my go-to npm lib for any numeric input fields, I can't express enough of my gratitude ❤️ Great work!
